version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.11.1
    steps:
      - checkout
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
            - yarn-packages-
      - run: yarn install --non-interactive --frozen-lockfile
      - save_cache:
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - /root/project/node_modules
      - run: yarn build
      - store_test_results:
          path: /tmp/reports
      - deploy:
          command: |
            if echo "${CIRCLE_TAG}" | grep -Eq '[0-9]+(\.[0-9]+)+(-[a-zA-Z]+[0-9]*)*'; then
              yarn circle-publish
            fi

workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/

