#!/usr/bin/env bash

set -eux

DIST="dist/conjure-typescript-${CIRCLE_TAG}.tgz"
POM="dist/conjure-typescript-${CIRCLE_TAG}.pom"
UPLOAD_URL="https://api.bintray.com/content/palantir/releases/conjure-typescript/${CIRCLE_TAG}/com/palantir/conjure/typescript/conjure-typescript/${CIRCLE_TAG}"

# Bundle up executable
mkdir -p "dist/conjure-typescript-${CIRCLE_TAG}"
chmod +x dist/bin/conjure-typescript
cp -rf dist/bin "dist/conjure-typescript-${CIRCLE_TAG}/"
tar -czf "$DIST" -C dist "conjure-typescript-${CIRCLE_TAG}/bin"

# Generate POM
{
    echo '<?xml version="1.0" encoding="UTF-8"?>'
    echo "<project"
    echo '    xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd"'
    echo '    xmlns="http://maven.apache.org/POM/4.0.0"'
    echo '    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">'
    echo "    <modelVersion>4.0.0</modelVersion>"
    echo "    <groupId>com.palantir.conjure.typescript</groupId>"
    echo "    <artifactId>conjure-typescript</artifactId>"
    echo "    <version>${CIRCLE_TAG}</version>"
    echo "    <packaging>tgz</packaging>"
    echo "</project>"
} > ${POM}

# Upload artifacts
set +x
BASIC_AUTH="${BINTRAY_USERNAME}:${BINTRAY_PASSWORD}"
curl --fail -v -X PUT "${UPLOAD_URL}/conjure-typescript-${CIRCLE_TAG}.pom" -T "${POM}" -u "${BASIC_AUTH}"
curl --fail -v -X PUT "${UPLOAD_URL}/conjure-typescript-${CIRCLE_TAG}.tgz?publish=1" -T "${DIST}" -u "${BASIC_AUTH}"
set -x
