#!/usr/bin/env bash

tarBall=dist/conjure-typescript.tgz
chmod +x dist/conjure-typescript
tar -czf "$tarBall" -C dist conjure-typescript
artifact_version=$CIRCLE_TAG
artifact_file="conjure-typescript-$artifact_version.tgz"

upload_url="https://api.bintray.com/content/palantir/releases/conjure-typescript/${artifact_version}/com/palantir/conjure/typescript/conjure-typescript/${artifact_version}/${artifact_file}"
echo "publishing $tarBall to $upload_url"
set +x
curl --fail -v -X PUT "$upload_url?publish=1" -T "$tarBall" -u $BINTRAY_USERNAME:$BINTRAY_PASSWORD
set -x
