#!/bin/bash

set -ex
set -o pipefail

if [ -z ${CIRCLECI+x} ]; then
    echo "Not on Circle; refusing to run."
    exit 1
fi

# Generate npmrc, ensure it is readable
echo "//registry.npmjs.org/:_authToken=${NPM_AUTH_TOKEN}" > .npmrc
chmod +r .npmrc

# Change package version to latest tag
npm version "$CIRCLE_TAG" --no-git-tag-version

# Package and publish
npm publish --access public
